name: Build and Deploy

on: 
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Initialize Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm build
      run: |
        npm ci
        npm run build
    - name: deploy
      uses: garygrossgarten/github-action-scp@release
      with:
        local: dist
        remote: httpdocs/amazer-view
        host: ${{ secrets.NETCUP_WEB_HOST }}
        username: ${{ secrets.NETCUP_WEB_USER }}
        password: ${{ secrets.NETCUP_WEB_PASSWORD }}
