name: Node CI

on: 
  push:
    branches: master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Initialize Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm build
      run: |
        npm ci
        npm run build
    - name: publish
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.NETCUP_WEB_HOST }}
        username: ${{ secrets.NETCUP_WEB_USER }}
        # key: ${{ secrets.NETCUP_WEB_KEY }}
        password: ${{ secrets.NETCUP_WEB_PASSWORD }}
        source: "dist/*"
        target: "httpdocs/amazer-view/"
