name: Node CI

on: 
  push:
    branches: master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Initialize Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm build
      run: |
        npm ci
        npm run build
    - name: publish
      run: |
        cd dist
        ls -la
