name: Node CI

on: 
  push:
    branches: master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Initialize Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: npm build
      run: |
        npm ci
        npm run build
    - name: publish
      uses: garygrossgarten/github-action-scp@release
        with:
          local: dist
          remote: httpdocs/amazer-view
          host: ${{ secrets.NETCUP_WEB_HOST }}
          username: ${{ secrets.NETCUP_WEB_USER }}
          password: ${{ secrets.NETCUP_WEB_PASSWORD }}
      # run: |
      #   echo "${{ secrets.NETCUP_WEB_KEY }}" > ./ssh_key
      #   ls -la
      #   cd ./dist
      #   scp -r -i ../ssh_key * ${{ secrets.NETCUP_WEB_USER }}@${{ secrets.NETCUP_WEB_HOST }}:httpdocs/amazer-view/
      # uses: horochx/deploy-via-scp@master
      # with:
      #   host: ${{ secrets.NETCUP_WEB_HOST }}
      #   port: 22
      #   user: ${{ secrets.NETCUP_WEB_USER }}
      #   key: ${{ secrets.NETCUP_WEB_KEY }}
      #   local: "dist"
      #   target: "/httpdocs/amazer-view"
